# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`

repos:
  - repo: local
    hooks:

    - id: ruff
      name: ruff
      entry: ruff --fix
      language: system
      types: [python]
      stages: [pre-commit]

    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: system
      types: [python]
      stages: [pre-commit]

    - id: mypy
      name: mypy
      entry: mypy --exclude tests --pretty
      language: system
      types: [python]
      stages: [pre-commit]

  - repo: https://github.com/dronetag/pre-commit-hooks
    rev: v1.0.0
    hooks:
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-merge-conflict
    - id: conventional-commit-msg
    - id: debug-statements
    - id: detect-private-key
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: end-of-file-fixer
    - id: trailing-whitespace
