name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository (full-depth)
      uses: actions/checkout@v4
      with: { fetch-depth: 0 } # Required to determine version

    - name: Get next release version
      uses: dronetag/actions/semantic-release@main
      id: semantic

    - name: Build package
      uses: dronetag/actions/build-python@main
      with:
        version: ${{ steps.semantic.outputs.version }}

    - name: Commit and tag
      if: ${{ steps.semantic.outputs.existed == 'false' }}
      uses: dronetag/actions/commit-and-tag@main
      with:
        version: ${{ steps.semantic.outputs.version }}
        git-add: changelog.md
        commit: true
        github-token: ${{ github.token }}

    - name: Release
      uses: dronetag/actions/release-python@main
      with:
        pypi_name: dronetag
        pypi_host: ${{ secrets.PRIV_PIP_HOST }}
        pypi_user: ${{ secrets.PRIV_PIP_USER }}
        pypi_pass: ${{ secrets.PRIV_PIP_PASSWORD }}
