name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository (full-depth)
      uses: actions/checkout@v4
      with: { fetch-depth: 0 } # Required to determine version

    - name: Get next release version
      uses: dronetag/actions/semantic-release@main
      id: semantic

    - name: Build package
      uses: dronetag/actions/build-python@main
      with:
        version: ${{ steps.semantic.outputs.version }}

    - name: Commit and tag
      if: ${{ steps.semantic.outputs.existed == 'false' }}
      uses: dronetag/actions/commit-and-tag@main
      with:
        version: ${{ steps.semantic.outputs.version }}
        tag-message: ${{ steps.semantic.outputs.changelog }}
        git-add: changelog.md
        commit: true
        github-token: ${{ github.token }}

    - name: Release
      uses: dronetag/actions/release-python@main
      with:
        pypi-name: dronetag
        pypi-host: ${{ secrets.PRIV_PIP_HOST }}
        pypi-user: ${{ secrets.PRIV_PIP_USER }}
        pypi-pass: ${{ secrets.PRIV_PIP_PASSWORD }}


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install tools
      run: python3 -m pip install --upgrade pip setuptools wheel

    - name: Install DEV dependencies
      run: pip install -e .[dev]

    - name: Run tests
      run: bash run_tests.sh
